version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-stage-app
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app   # dev mode